github:
  access-token-param:
    client_id: b0e605039d179df070c4
    client_secret: 398ac962505586d8b868110ee07bafa0951091fc
    redirect_uri: http://localhost:8080/callback
  api:
    access_token_api: https://github.com/login/oauth/access_token
    get_user_api: https://api.github.com/user
    authorize_api: https://github.com/login/oauth/authorize
    scope: user

spring:
  datasource:
    url: jdbc:h2:E:/H2DB/community
    driver-class-name: org.h2.Driver
    username: sa
    password: "123"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
